language: node_js
node_js:
- iojs-v2.0.0
before_install:
- npm install -g npm@latest
deploy:
  provider: npm
  on:
    tags: true
    repo: aldrinleal/muse
env:
  global:
    NPM_TOKEN:
      secure: r/+yw3qAQ5XW2O8/+0ZjMiA/Fqr/UWvYMrV1Uy2B6zftot2EHWPULF0Zb6T+LAAjr0tDNvMEA6LNop+p3C6FMTrHEkL0MR3vo1kyIU8yj3YilESYJjjFd2OLbw+Vxkxnxdpue4CoeZH0iQk2CxFjF2BNSoBCgYgcU3xpNTEaJPVOi1cQcL/TvFJrk3mA+TXHjNBp+68ph4O49FOXcX42w9ZNQDOLBAC1+n9ouvT9GnpeLgRSThae4p8PE1yA768T7dcElIPoB93TMU4H426ObtHww8KNHyA/ME0HstwGG+wsMxrEmVCwBWn0G0JEat40AU25I7dqcKiANXoQzeCgfFy2j85wglmakEtUsoH0l+S/YJb2glnaPWdw/z6EVatTeWwdYHu+b8BS6Ax296IZg82LQm8apwvEDTHjYrMHMkfOgOc9XVjk6wft/V6W7fYreH9XzS//x2nk3/4LZXxryqnEGwPPHE8+srzIxfZVJ0GhzRaG0/hub2D91Yy40ZF9In6YfcNiY3NuBVZa3WUAB7cJWkGxf+QczktFdlUfM/dQyN/NHuHNkidTQKzU+NWJAYERHS2OtCAFR2/8qZ69K2QtrdWDtqKDspDW7yzyzIOXZNd/ZDUbbyg4WfEl3busInZBxaxODe/eRyIuPkxCbehT8lpTyQ8bYkH81qMT0p4=
