language: node_js
node_js:
- iojs-v2.0.0
before_install:
- npm install -g npm@latest
deploy:
  provider: npm
  email: aldrin+npmjs@leal.eng.br
  clean_up: false
  api_key:
    secure: qbxOa+UxKJjNKfniMTltTjooxINN4WuSsDA5X3hnSioW4lhikxop8DPlsOwQu3GH5iTUxSZMWVfq59LI7JqH2u0l+f2NrLvNBILvj5eXiVi++mejVXJSqva7GgRZSriEXkjASoXTrw9zv8Q4ILZxlOltElDAmRy1JsE4qiQHctNKIl+Xau36fDBMtuLPPpwRmoObfFDPl2VncWcWpcu7kJrldEHDFuq0UFCgQAytBKvDAM6VBvhkhYeeKr28LYggc0I2Aq/eX2DgVIEIyphoc6wfI2du++6eRnHlCDN+0X3qdgQAnFtAgZkLv87RNx+2lFeqGO786A5fbmmIW5DlYSglqHGxkNmdDPcT2DbXy1KFAru89hfdNbnVHkgoCGFXYB7mwAKFF5s+RZvtJ5WnOz+OL955/xLI6lX+t9uzPG+KkulUZlYWWcaIKLDUVPJWrdygwL+Vkd2ST4eneUoY+TwKHL8hylrhqjUODleENLfKtvoAnAbbwGJV0ESMVr48qJj013oBpzDt9S63qj2Cv7pzgESgyiDkKh4ui1KCrgeYWXSDerprKx5ahstfO52Y/nmeJDt8hE6nEOen+HaFT8bTQ/lYlG5B5C4+Sq/SMx0nlmZvL0CbC1sETxGy//C9uJFyQnvQuFhsclbk9XOY8qxKheNBGv8M+AUtuvIv7ws=
  on:
    tags: true
    repo: aldrinleal/muse
